CREATE TABLE produtos (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  valor DECIMAL(19, 2) NOT NULL,
  tipo_cobranca VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP NOT NULL
)
